version: "3.9"

services:

  backend:
    image: tuusuario/backend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: tuusuario/frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend