# Generated by Django 6.0.2 on 2026-03-07 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Crear registro'), ('EDITAR', 'Editar registro'), ('ELIMINAR', 'Eliminar registro'), ('CAMBIAR_ESTADO', 'Cambiar estado'), ('EXPORTAR', 'Exportar reporte'), ('COMPRA', 'Compra'), ('PEDIDO', 'Pedido'), ('PAGO', 'Pago'), ('OTRO', 'Otro')], max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('datos_extra', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
    ]
